In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

pd_data = pd.read_csv('./park.csv')
pd_data

,지자체명,공원구분,공원명,위도,경도,공원면적,지정고시일
0,서울특별시,소공원,녹색소공원,37.539217,126.962694,1569.9,2012-10-19
1,세종특별자치시,소공원,푸름샘 소공원(소1-1),36.516117,127.233781,1820.0,2011-08-05
2,세종특별자치시,소공원,솔숲 소공원(소1-2),36.508995,127.230040,1037.0,2011-08-05
3,세종특별자치시,수변공원,마디꽃 수변공원(수1-1),36.495962,127.257316,4928.0,2007-07-04
4,세종특별자치시,수변공원,꽃 수변공원(수2-3),36.473133,127.254482,3575.0,2009-01-07
...,...,...,...,...,...,...,...
17576,서울특별시,기타,방배,37.474225,126.995298,210517.2,NaN
17577,서울특별시,기타,말죽거리,37.480885,127.030469,280822.6,NaN
17578,서울특별시,근린공원,서리풀,37.484654,127.000420,465938.3,NaN
17579,서울특별시,근린공원,방배,37.470535,126.989600,74847.6,NaN
17580,서울특별시,근린공원,말죽거리,37.479294,127.029304,132020.3,NaN

In [30]:
a = pd_data[['지자체명', '공원면적']]
b = a.groupby('지자체명').mean()

c= pd_data[['공원구분', '공원면적']]
d= c.groupby('공원구분').mean()

In [31]:
b

                 공원면적
지자체명
강원도      28059.026863
경기도      23717.022300
경상남도     32619.131877
경상북도     25070.352861
광주광역시    18449.462205
대구광역시    30272.605705
대전광역시    39935.903596
부산광역시    46690.323042
서울특별시    52393.388293
세종특별자치시  39879.471429
울산광역시    48720.318630
인천광역시    40854.045874
전라남도     37908.341754
전라북도     63707.042387
제주특별자치도  40016.622041
충청남도     25852.038492
충청북도     28780.994158

In [38]:
d

                공원면적
공원구분
근린공원    1.023159e+05
기타      6.453024e+04
도시농업공원  8.486678e+05
도시자연공원  3.079347e+06
마을마당    1.115388e+03
묘지공원    5.532787e+05
문화공원    4.507657e+04
소공원     2.810124e+03
수변공원    4.137554e+04
어린이공원   3.552056e+03
역사공원    6.268933e+04
주제공원    3.128945e+04
체육공원    8.161599e+04